package DifyCore

type XSharedEnv struct {
	LOGLEVEL                              string `yaml:"LOG_LEVEL"`
	LOGFILE                               string `yaml:"LOG_FILE"`
	DEBUG                                 string `yaml:"DEBUG"`
	FLASKDEBUG                            string `yaml:"FLASK_DEBUG"`
	SECRETKEY                             string `yaml:"SECRET_KEY"`
	INITPASSWORD                          string `yaml:"INIT_PASSWORD"`
	CONSOLEWEBURL                         string `yaml:"CONSOLE_WEB_URL"`
	CONSOLEAPIURL                         string `yaml:"CONSOLE_API_URL"`
	SERVICEAPIURL                         string `yaml:"SERVICE_API_URL"`
	APPWEBURL                             string `yaml:"APP_WEB_URL"`
	CHECKUPDATEURL                        string `yaml:"CHECK_UPDATE_URL"`
	OPENAIAPIBASE                         string `yaml:"OPENAI_API_BASE"`
	FILESURL                              string `yaml:"FILES_URL"`
	FILESACCESSTIMEOUT                    string `yaml:"FILES_ACCESS_TIMEOUT"`
	APPMAXACTIVEREQUESTS                  string `yaml:"APP_MAX_ACTIVE_REQUESTS"`
	MIGRATIONENABLED                      string `yaml:"MIGRATION_ENABLED"`
	DEPLOYENV                             string `yaml:"DEPLOY_ENV"`
	DIFYBINDADDRESS                       string `yaml:"DIFY_BIND_ADDRESS"`
	DIFYPORT                              string `yaml:"DIFY_PORT"`
	SERVERWORKERAMOUNT                    string `yaml:"SERVER_WORKER_AMOUNT"`
	SERVERWORKERCLASS                     string `yaml:"SERVER_WORKER_CLASS"`
	CELERYWORKERCLASS                     string `yaml:"CELERY_WORKER_CLASS"`
	GUNICORNTIMEOUT                       string `yaml:"GUNICORN_TIMEOUT"`
	CELERYWORKERAMOUNT                    string `yaml:"CELERY_WORKER_AMOUNT"`
	CELERYAUTOSCALE                       string `yaml:"CELERY_AUTO_SCALE"`
	CELERYMAXWORKERS                      string `yaml:"CELERY_MAX_WORKERS"`
	CELERYMINWORKERS                      string `yaml:"CELERY_MIN_WORKERS"`
	APITOOLDEFAULTCONNECTTIMEOUT          string `yaml:"API_TOOL_DEFAULT_CONNECT_TIMEOUT"`
	APITOOLDEFAULTREADTIMEOUT             string `yaml:"API_TOOL_DEFAULT_READ_TIMEOUT"`
	DBUSERNAME                            string `yaml:"DB_USERNAME"`
	DBPASSWORD                            string `yaml:"DB_PASSWORD"`
	DBHOST                                string `yaml:"DB_HOST"`
	DBPORT                                string `yaml:"DB_PORT"`
	DBDATABASE                            string `yaml:"DB_DATABASE"`
	SQLALCHEMYPOOLSIZE                    string `yaml:"SQLALCHEMY_POOL_SIZE"`
	SQLALCHEMYPOOLRECYCLE                 string `yaml:"SQLALCHEMY_POOL_RECYCLE"`
	SQLALCHEMYECHO                        string `yaml:"SQLALCHEMY_ECHO"`
	REDISHOST                             string `yaml:"REDIS_HOST"`
	REDISPORT                             string `yaml:"REDIS_PORT"`
	REDISUSERNAME                         string `yaml:"REDIS_USERNAME"`
	REDISPASSWORD                         string `yaml:"REDIS_PASSWORD"`
	REDISUSESSL                           string `yaml:"REDIS_USE_SSL"`
	REDISDB                               int    `yaml:"REDIS_DB"`
	CELERYBROKERURL                       string `yaml:"CELERY_BROKER_URL"`
	BROKERUSESSL                          string `yaml:"BROKER_USE_SSL"`
	WEBAPICORSALLOWORIGINS                string `yaml:"WEB_API_CORS_ALLOW_ORIGINS"`
	CONSOLECORSALLOWORIGINS               string `yaml:"CONSOLE_CORS_ALLOW_ORIGINS"`
	STORAGETYPE                           string `yaml:"STORAGE_TYPE"`
	STORAGELOCALPATH                      string `yaml:"STORAGE_LOCAL_PATH"`
	S3USEAWSMANAGEDIAM                    string `yaml:"S3_USE_AWS_MANAGED_IAM"`
	S3ENDPOINT                            string `yaml:"S3_ENDPOINT"`
	S3BUCKETNAME                          string `yaml:"S3_BUCKET_NAME"`
	S3ACCESSKEY                           string `yaml:"S3_ACCESS_KEY"`
	S3SECRETKEY                           string `yaml:"S3_SECRET_KEY"`
	S3REGION                              string `yaml:"S3_REGION"`
	AZUREBLOBACCOUNTNAME                  string `yaml:"AZURE_BLOB_ACCOUNT_NAME"`
	AZUREBLOBACCOUNTKEY                   string `yaml:"AZURE_BLOB_ACCOUNT_KEY"`
	AZUREBLOBCONTAINERNAME                string `yaml:"AZURE_BLOB_CONTAINER_NAME"`
	AZUREBLOBACCOUNTURL                   string `yaml:"AZURE_BLOB_ACCOUNT_URL"`
	GOOGLESTORAGEBUCKETNAME               string `yaml:"GOOGLE_STORAGE_BUCKET_NAME"`
	GOOGLESTORAGESERVICEACCOUNTJSONBASE64 string `yaml:"GOOGLE_STORAGE_SERVICE_ACCOUNT_JSON_BASE64"`
	ALIYUNOSSBUCKETNAME                   string `yaml:"ALIYUN_OSS_BUCKET_NAME"`
	ALIYUNOSSACCESSKEY                    string `yaml:"ALIYUN_OSS_ACCESS_KEY"`
	ALIYUNOSSSECRETKEY                    string `yaml:"ALIYUN_OSS_SECRET_KEY"`
	ALIYUNOSSENDPOINT                     string `yaml:"ALIYUN_OSS_ENDPOINT"`
	ALIYUNOSSREGION                       string `yaml:"ALIYUN_OSS_REGION"`
	ALIYUNOSSAUTHVERSION                  string `yaml:"ALIYUN_OSS_AUTH_VERSION"`
	ALIYUNOSSPATHS                        string `yaml:"ALIYUN_OSS_PATHS"`
	TENCENTCOSBUCKETNAME                  string `yaml:"TENCENT_COS_BUCKET_NAME"`
	TENCENTCOSSECRETKEY                   string `yaml:"TENCENT_COS_SECRET_KEY"`
	TENCENTCOSSECRETID                    string `yaml:"TENCENT_COS_SECRET_ID"`
	TENCENTCOSREGION                      string `yaml:"TENCENT_COS_REGION"`
	TENCENTCOSSCHEME                      string `yaml:"TENCENT_COS_SCHEME"`
	OCIENDPOINT                           string `yaml:"OCI_ENDPOINT"`
	OCIBUCKETNAME                         string `yaml:"OCI_BUCKET_NAME"`
	OCIACCESSKEY                          string `yaml:"OCI_ACCESS_KEY"`
	OCISECRETKEY                          string `yaml:"OCI_SECRET_KEY"`
	OCIREGION                             string `yaml:"OCI_REGION"`
	VECTORSTORE                           string `yaml:"VECTOR_STORE"`
	WEAVIATEENDPOINT                      string `yaml:"WEAVIATE_ENDPOINT"`
	WEAVIATEAPIKEY                        string `yaml:"WEAVIATE_API_KEY"`
	QDRANTURL                             string `yaml:"QDRANT_URL"`
	QDRANTAPIKEY                          string `yaml:"QDRANT_API_KEY"`
	QDRANTCLIENTTIMEOUT                   string `yaml:"QDRANT_CLIENT_TIMEOUT"`
	QDRANTGRPCENABLED                     string `yaml:"QDRANT_GRPC_ENABLED"`
	QDRANTGRPCPORT                        string `yaml:"QDRANT_GRPC_PORT"`
	MILVUSHOST                            string `yaml:"MILVUS_HOST"`
	MILVUSPORT                            string `yaml:"MILVUS_PORT"`
	MILVUSUSER                            string `yaml:"MILVUS_USER"`
	MILVUSPASSWORD                        string `yaml:"MILVUS_PASSWORD"`
	MILVUSSECURE                          string `yaml:"MILVUS_SECURE"`
	MYSCALEHOST                           string `yaml:"MYSCALE_HOST"`
	MYSCALEPORT                           string `yaml:"MYSCALE_PORT"`
	MYSCALEUSER                           string `yaml:"MYSCALE_USER"`
	MYSCALEPASSWORD                       string `yaml:"MYSCALE_PASSWORD"`
	MYSCALEDATABASE                       string `yaml:"MYSCALE_DATABASE"`
	MYSCALEFTSPARAMS                      string `yaml:"MYSCALE_FTS_PARAMS"`
	RELYTHOST                             string `yaml:"RELYT_HOST"`
	RELYTPORT                             string `yaml:"RELYT_PORT"`
	RELYTUSER                             string `yaml:"RELYT_USER"`
	RELYTPASSWORD                         string `yaml:"RELYT_PASSWORD"`
	RELYTDATABASE                         string `yaml:"RELYT_DATABASE"`
	PGVECTORHOST                          string `yaml:"PGVECTOR_HOST"`
	PGVECTORPORT                          string `yaml:"PGVECTOR_PORT"`
	PGVECTORUSER                          string `yaml:"PGVECTOR_USER"`
	PGVECTORPASSWORD                      string `yaml:"PGVECTOR_PASSWORD"`
	PGVECTORDATABASE                      string `yaml:"PGVECTOR_DATABASE"`
	TIDBVECTORHOST                        string `yaml:"TIDB_VECTOR_HOST"`
	TIDBVECTORPORT                        string `yaml:"TIDB_VECTOR_PORT"`
	TIDBVECTORUSER                        string `yaml:"TIDB_VECTOR_USER"`
	TIDBVECTORPASSWORD                    string `yaml:"TIDB_VECTOR_PASSWORD"`
	TIDBVECTORDATABASE                    string `yaml:"TIDB_VECTOR_DATABASE"`
	ORACLEHOST                            string `yaml:"ORACLE_HOST"`
	ORACLEPORT                            string `yaml:"ORACLE_PORT"`
	ORACLEUSER                            string `yaml:"ORACLE_USER"`
	ORACLEPASSWORD                        string `yaml:"ORACLE_PASSWORD"`
	ORACLEDATABASE                        string `yaml:"ORACLE_DATABASE"`
	CHROMAHOST                            string `yaml:"CHROMA_HOST"`
	CHROMAPORT                            string `yaml:"CHROMA_PORT"`
	CHROMATENANT                          string `yaml:"CHROMA_TENANT"`
	CHROMADATABASE                        string `yaml:"CHROMA_DATABASE"`
	CHROMAAUTHPROVIDER                    string `yaml:"CHROMA_AUTH_PROVIDER"`
	CHROMAAUTHCREDENTIALS                 string `yaml:"CHROMA_AUTH_CREDENTIALS"`
	ELASTICSEARCHHOST                     string `yaml:"ELASTICSEARCH_HOST"`
	ELASTICSEARCHPORT                     string `yaml:"ELASTICSEARCH_PORT"`
	ELASTICSEARCHUSERNAME                 string `yaml:"ELASTICSEARCH_USERNAME"`
	ELASTICSEARCHPASSWORD                 string `yaml:"ELASTICSEARCH_PASSWORD"`
	KIBANAPORT                            string `yaml:"KIBANA_PORT"`
	ANALYTICDBKEYID                       string `yaml:"ANALYTICDB_KEY_ID"`
	ANALYTICDBKEYSECRET                   string `yaml:"ANALYTICDB_KEY_SECRET"`
	ANALYTICDBREGIONID                    string `yaml:"ANALYTICDB_REGION_ID"`
	ANALYTICDBINSTANCEID                  string `yaml:"ANALYTICDB_INSTANCE_ID"`
	ANALYTICDBACCOUNT                     string `yaml:"ANALYTICDB_ACCOUNT"`
	ANALYTICDBPASSWORD                    string `yaml:"ANALYTICDB_PASSWORD"`
	ANALYTICDBNAMESPACE                   string `yaml:"ANALYTICDB_NAMESPACE"`
	ANALYTICDBNAMESPACEPASSWORD           string `yaml:"ANALYTICDB_NAMESPACE_PASSWORD"`
	OPENSEARCHHOST                        string `yaml:"OPENSEARCH_HOST"`
	OPENSEARCHPORT                        string `yaml:"OPENSEARCH_PORT"`
	OPENSEARCHUSER                        string `yaml:"OPENSEARCH_USER"`
	OPENSEARCHPASSWORD                    string `yaml:"OPENSEARCH_PASSWORD"`
	OPENSEARCHSECURE                      string `yaml:"OPENSEARCH_SECURE"`
	TENCENTVECTORDBURL                    string `yaml:"TENCENT_VECTOR_DB_URL"`
	TENCENTVECTORDBAPIKEY                 string `yaml:"TENCENT_VECTOR_DB_API_KEY"`
	TENCENTVECTORDBTIMEOUT                string `yaml:"TENCENT_VECTOR_DB_TIMEOUT"`
	TENCENTVECTORDBUSERNAME               string `yaml:"TENCENT_VECTOR_DB_USERNAME"`
	TENCENTVECTORDBDATABASE               string `yaml:"TENCENT_VECTOR_DB_DATABASE"`
	TENCENTVECTORDBSHARD                  string `yaml:"TENCENT_VECTOR_DB_SHARD"`
	TENCENTVECTORDBREPLICAS               string `yaml:"TENCENT_VECTOR_DB_REPLICAS"`
	UPLOADFILESIZELIMIT                   string `yaml:"UPLOAD_FILE_SIZE_LIMIT"`
	UPLOADFILEBATCHLIMIT                  string `yaml:"UPLOAD_FILE_BATCH_LIMIT"`
	ETLTYPE                               string `yaml:"ETL_TYPE"`
	UNSTRUCTUREDAPIURL                    string `yaml:"UNSTRUCTURED_API_URL"`
	MULTIMODALSENDIMAGEFORMAT             string `yaml:"MULTIMODAL_SEND_IMAGE_FORMAT"`
	UPLOADIMAGEFILESIZELIMIT              string `yaml:"UPLOAD_IMAGE_FILE_SIZE_LIMIT"`
	SENTRYDSN                             string `yaml:"SENTRY_DSN"`
	SENTRYTRACESSAMPLERATE                string `yaml:"SENTRY_TRACES_SAMPLE_RATE"`
	SENTRYPROFILESSAMPLERATE              string `yaml:"SENTRY_PROFILES_SAMPLE_RATE"`
	NOTIONINTEGRATIONTYPE                 string `yaml:"NOTION_INTEGRATION_TYPE"`
	NOTIONCLIENTSECRET                    string `yaml:"NOTION_CLIENT_SECRET"`
	NOTIONCLIENTID                        string `yaml:"NOTION_CLIENT_ID"`
	NOTIONINTERNALSECRET                  string `yaml:"NOTION_INTERNAL_SECRET"`
	MAILTYPE                              string `yaml:"MAIL_TYPE"`
	MAILDEFAULTSENDFROM                   string `yaml:"MAIL_DEFAULT_SEND_FROM"`
	SMTPSERVER                            string `yaml:"SMTP_SERVER"`
	SMTPPORT                              string `yaml:"SMTP_PORT"`
	SMTPUSERNAME                          string `yaml:"SMTP_USERNAME"`
	SMTPPASSWORD                          string `yaml:"SMTP_PASSWORD"`
	SMTPUSETLS                            string `yaml:"SMTP_USE_TLS"`
	SMTPOPPORTUNISTICTLS                  string `yaml:"SMTP_OPPORTUNISTIC_TLS"`
	RESENDAPIKEY                          string `yaml:"RESEND_API_KEY"`
	RESENDAPIURL                          string `yaml:"RESEND_API_URL"`
	INDEXINGMAXSEGMENTATIONTOKENSLENGTH   string `yaml:"INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH"`
	INVITEEXPIRYHOURS                     string `yaml:"INVITE_EXPIRY_HOURS"`
	RESETPASSWORDTOKENEXPIRYHOURS         string `yaml:"RESET_PASSWORD_TOKEN_EXPIRY_HOURS"`
	CODEEXECUTIONENDPOINT                 string `yaml:"CODE_EXECUTION_ENDPOINT"`
	CODEEXECUTIONAPIKEY                   string `yaml:"CODE_EXECUTION_API_KEY"`
	CODEMAXNUMBER                         string `yaml:"CODE_MAX_NUMBER"`
	CODEMINNUMBER                         string `yaml:"CODE_MIN_NUMBER"`
	CODEMAXDEPTH                          string `yaml:"CODE_MAX_DEPTH"`
	CODEMAXPRECISION                      string `yaml:"CODE_MAX_PRECISION"`
	CODEMAXSTRINGLENGTH                   string `yaml:"CODE_MAX_STRING_LENGTH"`
	TEMPLATETRANSFORMMAXLENGTH            string `yaml:"TEMPLATE_TRANSFORM_MAX_LENGTH"`
	CODEMAXSTRINGARRAYLENGTH              string `yaml:"CODE_MAX_STRING_ARRAY_LENGTH"`
	CODEMAXOBJECTARRAYLENGTH              string `yaml:"CODE_MAX_OBJECT_ARRAY_LENGTH"`
	CODEMAXNUMBERARRAYLENGTH              string `yaml:"CODE_MAX_NUMBER_ARRAY_LENGTH"`
	SSRFPROXYHTTPURL                      string `yaml:"SSRF_PROXY_HTTP_URL"`
	SSRFPROXYHTTPSURL                     string `yaml:"SSRF_PROXY_HTTPS_URL"`
}

type HealthCheck struct {
	Test     []string `yaml:"test"`
	Interval string   `yaml:"interval,omitempty"`
	Timeout  string   `yaml:"timeout,omitempty"`
	Retries  int      `yaml:"retries,omitempty"`
}
