package Define

const (
	DEFAULT_DOCKER_IMAGE_DIFY_API         = "langgenius/dify-api"
	DEFAULT_DOCKER_IMAGE_VERSION_DIFY_API = "0.8.0"

	DEFAULT_DOCKER_IMAGE_DIFY_WORKER         = "langgenius/dify-api"
	DEFAULT_DOCKER_IMAGE_VERSION_DIFY_WORKER = "0.8.0"

	DEFAULT_DOCKER_IMAGE_DIFY_WEB         = "langgenius/dify-web"
	DEFAULT_DOCKER_IMAGE_VERSION_DIFY_WEB = "0.8.0"

	DEFAULT_DOCKER_IMAGE_DIFY_REDIS         = "redis"
	DEFAULT_DOCKER_IMAGE_VERSION_DIFY_REDIS = "6-alpine"

	DEFAULT_DOCKER_IMAGE_DIFY_POSTGRES         = "postgres"
	DEFAULT_DOCKER_IMAGE_VERSION_DIFY_POSTGRES = "15-alpine"

	DEFAULT_DOCKER_IMAGE_DIFY_NGINX         = "nginx"
	DEFAULT_DOCKER_IMAGE_VERSION_DIFY_NGINX = "latest"

	DEFAULT_DOCKER_IMAGE_DIFY_SANDBOX         = "langgenius/dify-sandbox"
	DEFAULT_DOCKER_IMAGE_VERSION_DIFY_SANDBOX = "0.2.7"

	DEFAULT_DOCKER_IMAGE_DIFY_SSRF_PROXY         = "ubuntu/squid"
	DEFAULT_DOCKER_IMAGE_VERSION_DIFY_SSRF_PROXY = "latest"

	DEFAULT_DOCKER_IMAGE_DIFY_CERTBOT         = "certbot/certbot"
	DEFAULT_DOCKER_IMAGE_VERSION_DIFY_CERTBOT = ""

	DEFAULT_DOCKER_IMAGE_DIFY_UNSTRUCTURED         = "downloads.unstructured.io/unstructured-io/unstructured-api"
	DEFAULT_DOCKER_IMAGE_DIFY_UNSTRUCTURED_VERSION = "latest"

	DEFAULT_DOCKER_IMAGE_VDB_CHROMA         = "ghcr.io/chroma-core/chroma"
	DEFAULT_DOCKER_IMAGE_VDB_CHROMA_VERSION = "0.5.1"

	DEFAULT_DOCKER_IMAGE_VDB_ELASTICSEARCH         = "docker.elastic.co/elasticsearch/elasticsearch"
	DEFAULT_DOCKER_IMAGE_VDB_ELASTICSEARCH_VERSION = "8.14.3"

	DEFAULT_DOCKER_IMAGE_VDB_MILVUS               = "milvusdb/milvus"
	DEFAULT_DOCKER_IMAGE_VDB_MILVUS_VERSION       = "v2.3.1"
	DEFAULT_DOCKER_IMAGE_VDB_MILVUS_ETCD          = "quay.io/coreos/etcd"
	DEFAULT_DOCKER_IMAGE_VDB_MILVUS_ETCD_VERSION  = "v3.5.5"
	DEFAULT_DOCKER_IMAGE_VDB_MILVUS_MINIO         = "minio/minio"
	DEFAULT_DOCKER_IMAGE_VDB_MILVUS_MINIO_VERSION = "RELEASE.2023-03-20T20-16-18Z"
)

const (
	DOCKER_SERVICE_DIFY_API = iota
	DOCKER_SERVICE_DIFY_WORKER
	DOCKER_SERVICE_DIFY_WEB
	DOCKER_SERVICE_DIFY_REDIS
	DOCKER_SERVICE_DIFY_POSTGRES
	DOCKER_SERVICE_DIFY_NGINX
	DOCKER_SERVICE_DIFY_SANDBOX
	DOCKER_SERVICE_DIFY_SSRF_PROXY
	DOCKER_SERVICE_DIFY_CERTBOT
	DOCKER_SERVICE_DIFY_UNSTRUCTURED

	DOCKER_SERVICE_VDB_CHROMA
	DOCKER_SERVICE_VDB_ELASTICSEARCH
	DOCKER_SERVICE_VDB_MILVUS
	DOCKER_SERVICE_VDB_MILVUS_ETCD
	DOCKER_SERVICE_VDB_MILVUS_MINIO
)
