package CustomConfig

type DockerImage struct {
	Image   string `json:"image"`
	Version string `json:"version"`
}

var DefaultDockerImages = func() map[int]DockerImage {
	return map[int]DockerImage{
		DOCKER_SERVICE_DIFY_API: {
			Image:   DEFAULT_DOCKER_IMAGE_DIFY_API,
			Version: DEFAULT_DOCKER_IMAGE_VERSION_DIFY_API,
		},
		DOCKER_SERVICE_DIFY_WORKER: {
			Image:   DEFAULT_DOCKER_IMAGE_DIFY_WORKER,
			Version: DEFAULT_DOCKER_IMAGE_VERSION_DIFY_WORKER,
		},
		DOCKER_SERVICE_DIFY_WEB: {
			Image:   DEFAULT_DOCKER_IMAGE_DIFY_WEB,
			Version: DEFAULT_DOCKER_IMAGE_VERSION_DIFY_WEB,
		},
		DOCKER_SERVICE_DIFY_REDIS: {
			Image:   DEFAULT_DOCKER_IMAGE_DIFY_REDIS,
			Version: DEFAULT_DOCKER_IMAGE_VERSION_DIFY_REDIS,
		},
		DOCKER_SERVICE_DIFY_POSTGRES: {
			Image:   DEFAULT_DOCKER_IMAGE_DIFY_POSTGRES,
			Version: DEFAULT_DOCKER_IMAGE_VERSION_DIFY_POSTGRES,
		},
		DOCKER_SERVICE_DIFY_NGINX: {
			Image:   DEFAULT_DOCKER_IMAGE_DIFY_NGINX,
			Version: DEFAULT_DOCKER_IMAGE_VERSION_DIFY_NGINX,
		},
		DOCKER_SERVICE_DIFY_SANDBOX: {
			Image:   DEFAULT_DOCKER_IMAGE_DIFY_SANDBOX,
			Version: DEFAULT_DOCKER_IMAGE_VERSION_DIFY_SANDBOX,
		},
		DOCKER_SERVICE_DIFY_SSRF_PROXY: {
			Image:   DEFAULT_DOCKER_IMAGE_DIFY_SSRF_PROXY,
			Version: DEFAULT_DOCKER_IMAGE_VERSION_DIFY_SSRF_PROXY,
		},
		DOCKER_SERVICE_DIFY_CERTBOT: {
			Image:   DEFAULT_DOCKER_IMAGE_DIFY_CERTBOT,
			Version: DEFAULT_DOCKER_IMAGE_VERSION_DIFY_CERTBOT,
		},
		DOCKER_SERVICE_DIFY_UNSTRUCTURED: {
			Image:   DEFAULT_DOCKER_IMAGE_DIFY_UNSTRUCTURED,
			Version: DEFAULT_DOCKER_IMAGE_DIFY_UNSTRUCTURED_VERSION,
		},
	}
}()

const (
	DOCKER_SERVICE_DIFY_API = iota
	DOCKER_SERVICE_DIFY_WORKER
	DOCKER_SERVICE_DIFY_WEB
	DOCKER_SERVICE_DIFY_REDIS
	DOCKER_SERVICE_DIFY_POSTGRES
	DOCKER_SERVICE_DIFY_NGINX
	DOCKER_SERVICE_DIFY_SANDBOX
	DOCKER_SERVICE_DIFY_SSRF_PROXY
	DOCKER_SERVICE_DIFY_CERTBOT
	DOCKER_SERVICE_DIFY_UNSTRUCTURED
)

func GetImage(imageType int) string {
	info, ok := DefaultDockerImages[DOCKER_SERVICE_DIFY_API]
	if ok {
		if info.Version == "" {
			return info.Image
		}
		return info.Image + ":" + info.Version
	}
	return "not-found"
}
